<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Connect Remote</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8d5a3770-f16d-492f-9fda-a9193d1452b4</testSuiteGuid>
   <testCaseLink>
      <guid>d82b5972-144b-472a-91d4-3d3a1814ab82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesh Config/Connect device/OL_21 Verify connect Remote success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>249122a2-e694-46c9-9a17-04fa7120d097</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54b16b6e-0aaa-4bdd-a5b8-e8151750e320</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>567ba0f4-d858-4ed1-9f96-da5db84e1a65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesh Config/Dashboard/OL_22 View list device success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71be9763-d58e-4673-a26b-5d27df0ecd51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>faa35863-d56b-4af9-9982-711e9fcfa13d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesh Config/Dashboard/OL_23 View wifi info success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d50f1e71-acb5-45be-a8f8-f4d6f4e71187</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
