<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Dashboard - Remote</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>21d7f0c8-acf4-4ed4-9a6d-787caff5c284</testSuiteGuid>
   <testCaseLink>
      <guid>2c4e2b65-9981-4659-b734-b1ef1cd3ce40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesh/Connect device/OL_21 Verify connect Remote success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>249122a2-e694-46c9-9a17-04fa7120d097</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54b16b6e-0aaa-4bdd-a5b8-e8151750e320</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b074e7f-d06e-4ca9-8c9a-ac5d961a0737</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesh/Dashboard/Local/OL_22 View list device success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71be9763-d58e-4673-a26b-5d27df0ecd51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48fc3c7f-5cb9-499c-b938-02d603a6585b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesh/Dashboard/Local/OL_23 View wifi info success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1ff010a0-8921-4286-816e-19a27614c46f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesh/Dashboard/Local/OL_24 View client device info success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90daac2a-d3c7-4f76-b566-5a81e80cfb5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d014563-8945-4019-b722-143b35fb8670</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesh/Dashboard/Local/OL_28 Update wifi infor success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8640d8e4-c60e-478f-9f42-8114d4fecb15</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
